name: Release

on:
  workflow_dispatch:
    branches: [ master ]
    inputs:
      notes:
        description: 'Release Notes'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate website with nuxt
        run: |
          git clone https://github.com/anthive/website.git
          cd website
          npm ci
          npm run generate
        env:
          API_URL: https://api.anthive.io/
          PROFILE_URL: https://profile.anthive.io/
          SANDBOX_STORAGE: https://storage.googleapis.com/anthive-prod-sandbox/
          SIM_VERSION: 5.0
          SANDBOX_API_URL: https://sandbox-luvkm7etwa-uc.a.run.app/
      - name: Archive prod pages
        uses: actions/upload-artifact@v2
        with:
          name: gh-pages
          path: website/dist
          retention-days: 1
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove old files
        run: |
          shopt -s extglob
          rm -r !("CNAME"|"README.md")
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: gh-pages
          path: /
      - name: Checking
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          ls -R
          echo "Done"
