name: Release

on:
  workflow_dispatch:
    branches: [ master ]
    inputs:
      notes:
        description: 'Release Notes'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        shopt -s extglob
        rm -r !("CNAME"|"README.md")
        git config user.name github-actions
        git config user.email github-actions@github.com
        git clone https://github.com/anthive/website.git
        cd website
        npm ci
        npm run generate
        cd ..
        cp -r website/dist/** .
        rm -rf website
        git add .
        git commit -m "Release: ${{ github.event.inputs.notes }}"
        echo "Done"
    - env:
        API_URL: https://api.anthive.io/
        PROFILE_URL: https://profile.anthive.io/
        SANDBOX_STORAGE: https://storage.googleapis.com/anthive-prod-sandbox/
        SIM_VERSION: 5.0
        SANDBOX_API_URL: https://sandbox-luvkm7etwa-uc.a.run.app/
